services:
  - type: web
    name: byteandbean
    runtime: static
    buildCommand: ""
    staticPublishPath: .
    pullRequestPreviewsEnabled: true
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=86400
      - path: /*.jpg
        name: Cache-Control
        value: public, max-age=2592000
      - path: /*.JPG
        name: Cache-Control
        value: public, max-age=2592000
      - path: /*.png
        name: Cache-Control
        value: public, max-age=2592000
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
